from pathlib import Path
import json

from agent_vars.cli import main
from agent_vars.contract import load_contract


EXAMPLE = Path("agent-vars.example.yaml").resolve()


def test_validate_resolves_required_values_by_phase(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    values = tmp_path / "values.json"
    values.write_text(json.dumps({"environment_value": {"NATS_URL": "nats://dev", "REDIS_URL": "redis://dev"}}), encoding="utf-8")
    result = main([
        "--contract", str(EXAMPLE),
        "validate",
        "--environment", "dev",
        "--overlay", "preview",
        "--service", "api-gateway",
        "--phase", "runtime",
        "--values", str(values),
    ])
    assert result == 0
    assert "contract valid" in capsys.readouterr().out


def test_skill_command_prints_packaged_skill(capsys):
    assert main(["skill"]) == 0
    output = capsys.readouterr().out
    assert "# Agent Vars Skill" in output
    assert "agent-vars --help" in output


def test_skill_command_can_print_packaged_skill_path(capsys):
    assert main(["skill", "--path"]) == 0
    output = capsys.readouterr().out.strip()
    assert output.endswith("agent_vars/SKILL.md")


def test_materialize_writes_default_env_target_from_template(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    contract = {
        "version": 1,
        "project": "demo",
        "environments": {"dev": {}},
        "services": {
            "web": {
                "root": ".",
                "env_files": [".env.local.example"],
                "requires": [
                    {"name": "APP_BASE_URL", "source": "APP_BASE_URL", "visibility": "internal", "phase": "runtime", "required": True},
                    {"name": "NEXT_PUBLIC_API_URL", "source": "NEXT_PUBLIC_API_URL", "visibility": "public", "phase": "build", "required": True},
                ],
            },
        },
    }
    contract_path = tmp_path / "agent-vars.json"
    values_path = tmp_path / "values.json"
    contract_path.write_text(json.dumps(contract), encoding="utf-8")
    values_path.write_text(
        json.dumps({"environment_value": {"APP_BASE_URL": "http://localhost:3000", "NEXT_PUBLIC_API_URL": "http://localhost:4000"}}),
        encoding="utf-8",
    )

    assert main(["--contract", str(contract_path), "materialize", "web", "--environment", "dev", "--values", str(values_path), "--strict"]) == 0
    assert capsys.readouterr().out == ""
    assert (tmp_path / ".env.local").read_text(encoding="utf-8") == (
        "# Generated by agent-vars materialize. Do not commit secrets.\n"
        "APP_BASE_URL=http://localhost:3000\n"
        "NEXT_PUBLIC_API_URL=http://localhost:4000\n"
    )


def test_materialize_resolves_active_provider_profile_without_mutating_provider(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    provider_values = tmp_path / "provider.json"
    provider_values.write_text('{"API_TOKEN":"provider-secret"}', encoding="utf-8")
    contract = {
        "version": 1,
        "project": "demo",
        "environments": {"dev": {"provider_profile": "local-dev"}},
        "providers": {"local-dev": {"kind": "local", "fixture": str(provider_values)}},
        "services": {
            "api": {
                "root": "services/api",
                "env_files": ["services/api/.env.example"],
                "requires": [{"name": "API_TOKEN", "source": "API_TOKEN", "visibility": "secret", "phase": "runtime", "required": True}],
            },
        },
    }
    contract_path = tmp_path / "agent-vars.json"
    contract_path.write_text(json.dumps(contract), encoding="utf-8")

    assert main(["--contract", str(contract_path), "materialize", "api", "--environment", "dev", "--strict"]) == 0
    assert capsys.readouterr().out == ""
    assert (tmp_path / "services" / "api" / ".env").read_text(encoding="utf-8") == (
        "# Generated by agent-vars materialize. Do not commit secrets.\n"
        "API_TOKEN=provider-secret\n"
    )
    assert json.loads(provider_values.read_text(encoding="utf-8")) == {"API_TOKEN": "provider-secret"}


def test_strict_materialize_fails_for_missing_required_values(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    result = main([
        "--contract", str(EXAMPLE),
        "materialize", "api-gateway",
        "--environment", "dev",
        "--overlay", "preview",
        "--strict",
        "--dry-run",
    ])
    assert result == 2
    assert "missing required values" in capsys.readouterr().err


def test_publish_renew_actions_and_cleanup_commands(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("AGENT_VARS_REGISTRY", str(tmp_path / "registry.json"))
    scope = ["--environment", "dev", "--overlay", "preview", "--sandbox", "s1", "--task", "t1"]
    assert main([
        "--contract", str(EXAMPLE), "publish",
        "service.api-gateway.primary.url", "https://api.example",
        *scope, "--service", "api-gateway", "--instance", "api.1", "--ttl", "1h",
    ]) == 0
    published = json.loads(capsys.readouterr().out)
    assert published["actions"][0]["action"] == "rebuild"

    assert main(["--contract", str(EXAMPLE), "renew", "api.1", *scope, "--service", "api-gateway", "--ttl", "2h"]) == 0
    assert "renewed: 1" in capsys.readouterr().out

    assert main(["--contract", str(EXAMPLE), "actions", *scope, "--service", "frontend"]) == 0
    actions = json.loads(capsys.readouterr().out)
    assert actions[0]["service"] == "frontend"

    assert main(["--contract", str(EXAMPLE), "ack-actions", str(actions[0]["publication"])]) == 0
    assert "acknowledged: 1" in capsys.readouterr().out

    assert main(["--contract", str(EXAMPLE), "cleanup", *scope]) == 0
    assert "deleted: 1" in capsys.readouterr().out


def test_resources_and_suggestions_select_provider_from_environment(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    fixture = tmp_path / "provider.json"
    fixture.write_text('{"NATS_URL":"secret"}', encoding="utf-8")
    contract = load_contract(EXAMPLE)
    contract["providers"]["gcp-dev"]["fixture"] = str(fixture)
    contract_path = tmp_path / "contract.json"
    contract_path.write_text(json.dumps(contract), encoding="utf-8")

    assert main(["--contract", str(contract_path), "resources", "--environment", "dev"]) == 0
    resources = json.loads(capsys.readouterr().out)
    assert resources[0]["name"] == "NATS_URL"

    suggestions_path = tmp_path / "suggestions.json"
    assert main(["--contract", str(contract_path), "suggest", "--environment", "dev", "--out", str(suggestions_path)]) == 0
    suggestions = json.loads(capsys.readouterr().out)
    assert any(item["required"] == "NATS_URL" and item["environment"] == "dev" for item in suggestions)


def test_trace_and_events_redact_values_by_default(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("AGENT_VARS_REGISTRY", str(tmp_path / "registry.json"))
    scope = ["--environment", "dev", "--overlay", "preview", "--sandbox", "s1", "--task", "t1"]
    assert main(["--contract", str(EXAMPLE), "publish", "service.api-gateway.primary.url", "https://secret", *scope, "--service", "api-gateway", "--instance", "api.1"]) == 0
    capsys.readouterr()
    assert main(["--contract", str(EXAMPLE), "trace", "service.api-gateway.primary.url", *scope]) == 0
    assert json.loads(capsys.readouterr().out)["value"] == "<redacted>"
    assert main(["--contract", str(EXAMPLE), "events", *scope, "--type", "publish"]) == 0
    assert json.loads(capsys.readouterr().out)[0]["value"] == "<redacted>"


def test_diff_compares_values_without_revealing_them(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    left = tmp_path / "left.json"
    right = tmp_path / "right.json"
    left.write_text('{"environment_value":{"NATS_URL":"nats://left"}}', encoding="utf-8")
    right.write_text('{"environment_value":{"NATS_URL":"nats://right"}}', encoding="utf-8")
    assert main([
        "--contract", str(EXAMPLE), "diff", "dev", "qa", "--service", "api-gateway",
        "--left-values", str(left), "--right-values", str(right),
    ]) == 0
    output = capsys.readouterr().out
    result = json.loads(output)
    assert next(item for item in result["values"] if item["name"] == "NATS_URL")["value_changed"] is True
    assert "nats://left" not in output


def test_materialize_and_unmount_file_secret_lifecycle(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    values = tmp_path / "values.json"
    values.write_text('{"environment_value":{"NATS_URL":"nats://dev","REDIS_URL":"redis://dev"}}', encoding="utf-8")
    file_values = tmp_path / "files.json"
    file_values.write_text('{"gcp_service_account":{"type":"service_account","project_id":"test"}}', encoding="utf-8")
    mount_root = tmp_path / "mounts"
    assert main([
        "--contract", str(EXAMPLE), "materialize", "api-gateway", "--environment", "dev", "--overlay", "preview",
        "--values", str(values), "--file-values", str(file_values), "--mount-root", str(mount_root), "--strict",
    ]) == 0
    capsys.readouterr()
    mounted = mount_root / "app/gcp-credentials/service-account.json"
    assert mounted.exists()
    assert main(["--contract", str(EXAMPLE), "unmount", "api-gateway", "--mount-root", str(mount_root)]) == 0
    result = json.loads(capsys.readouterr().out)
    assert result["removed"] == [str(mounted)]
    assert not mounted.exists()


def test_validate_consumes_environment_scoped_approved_binding(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    fixture = tmp_path / "gcp-values.json"
    fixture.write_text('{"API_TOKEN":"provider-value"}', encoding="utf-8")
    contract = load_contract(EXAMPLE)
    contract["providers"]["gcp-dev"]["fixture"] = str(fixture)
    contract["services"]["api-gateway"]["requires"] = [{
        "name": "API_TOKEN", "source": "review.required", "visibility": "secret", "phase": "runtime", "required": True,
    }]
    contract_path = tmp_path / "contract.json"
    contract_path.write_text(json.dumps(contract), encoding="utf-8")
    bindings = tmp_path / "approvals.json"
    bindings.write_text(json.dumps([{
        "service": "api-gateway", "required": "API_TOKEN", "suggested_source": "gcp-dev.API_TOKEN",
        "environment": "dev", "status": "approved",
    }]), encoding="utf-8")
    assert main([
        "--contract", str(contract_path), "validate", "--environment", "dev", "--service", "api-gateway",
        "--phase", "runtime", "--bindings", str(bindings),
    ]) == 0
    assert "contract valid" in capsys.readouterr().out


def test_doctor_requires_verified_file_mount(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    values = tmp_path / "values.json"
    values.write_text('{"environment_value":{"NATS_URL":"nats://dev","REDIS_URL":"redis://dev"}}', encoding="utf-8")
    result = main([
        "--contract", str(EXAMPLE), "doctor", "api-gateway", "--environment", "dev", "--overlay", "preview",
        "--values", str(values),
    ])
    assert result == 1
    output = json.loads(capsys.readouterr().out)
    file_diagnostic = next(item for item in output["diagnostics"] if item["variable"] == "GOOGLE_APPLICATION_CREDENTIALS")
    assert file_diagnostic["status"] == "missing"
    assert "mount-root" in file_diagnostic["hint"]
